### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by Kaviyarasan-M** [Acuant/AcuantAndroidMobileSDKV10#3]
I tried to capture facial after capturing the passport document, but the app gets crashed.

The below is the log error which we get:

 Process: com.acuant.sampleapp, PID: 21683
    java.io.FileNotFoundException: https://services.assureid.net/AssureIDService/Document/19bed931-98f6-441d-9e1b-f27932fbc37d/Image?side=Front&light=White
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:254)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
        at com.acuant.sampleapp.MainActivity.loadAssureIDImage(MainActivity.kt:633)
        at com.acuant.sampleapp.MainActivity$processImages$1$imageProcessingFinished$5.invoke(MainActivity.kt:449)
        at com.acuant.sampleapp.MainActivity$processImages$1$imageProcessingFinished$5.invoke(MainActivity.kt:374)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

**Comment by awjones76** [comment]
I'm having the same issue. The web service call is returning a 404.

**Comment by tbehera** [comment]
@awjones76 Please create a support ticket at https://support.acuant.com. So that we can get details of your credentials to fix it.

**Comment by awjones76** [comment]
@tbehera Already done. Thanks!
